#!/usr/bin/env python
#encoding=utf8
from __future__ import division
import argparse, time
# import sys,  pdb, argparse, time
# b = pdb.set_trace   #调试
from path import path
from Bio import SeqIO
def main():
    function = '序列文件的格式转换'
    parse = argparse.ArgumentParser(prog='qiime_pipline', 
        description=function)
    parse.add_argument('fromFile')
    parse.add_argument('fromFormat')
    parse.add_argument('toDir')
    parse.add_argument('toFormat')
    args = parse.parse_args()
    # fq = args.fq_file  # fastq file path
    # out = args.outDir
    # sampleID = args.sampleID
    toFile = '%s/%s.%s' % (args.toDir, path(args.fromFile).namebase, args.toFormat)
    count = SeqIO.convert(args.fromFile, args.fromFormat, toFile, args.toFormat)
    if args.toFormat == 'qual' and args.fromFormat in ('fastq', 'sff'):
        toFileFa = '%s/%s.fasta' % (args.toDir, path(args.fromFile).namebase)
        SeqIO.convert(args.fromFile, args.fromFormat, toFileFa, 'fasta')
    print "Converted %i records" % count  #统计转换序列的个数。

main()
