#!/usr/bin/env python
#encoding=utf8

import os, sys, argparse, textwrap, ConfigParser
import logging
from michelia import path, run_cmd
from ruffus import *

parser = argparse.ArgumentParser(description='''
            human-pipe-dsg 200 "{'L374N': 115, 'L374T': 115}" "{'L374N': 39548755, 'L374T': 38271678}"
            这是人差异剪接的流程
            ''')

parser.add_argument('sample_id_length', type=str,
                    help="这个是样品的必须信息,  包括样品的id 和 样品测序的长度. 格式如: {'L374N': 115, 'L374T': 115}")
parser.add_argument('sample_map_read_num', type=str,
                    help="这个是样品的必须信息,  包括样品的id 和 样品测序的长度. 格式如: {'L374N': 39548755, 'L374T': 38271678}")
parser.add_argument('-v', '--verbose', dest='verbose',
        action="count", default=3,
        help="Print more detailed messages for each additional verbose level. E.g. run_parallel_blast --verbose --verbose --verbose ... (or -vvv)")

parser.add_argument("-j", "--jobs", dest="jobs",
                    default=4,
                    metavar="jobs",
                    type=int,
                    help="Specifies the number of jobs (operations) to run in parallel. default is 4.")

parser.add_argument('-f', "--flowchart", dest="flowchart",
                    metavar="FILE",
                    type=str,
                    help="Print flowchart of the pipeline to FILE. Flowchart format "
                       "depends on extension. Alternatives include ('.dot', '.jpg', "
                       "'*.svg', '*.png' ,'.pdf' etc). Formats other than '.dot' require "
                       "the dot program to be installed (http://www.graphviz.org/).")
parser.add_argument("-n", "--just_print", dest="just_print",
                    action="store_true", default=False,
                    help="Only print a trace (description) of the pipeline. "
                         " The level of detail is set by --verbose.")
# parser.add_argument("-p", dest="p",
#                     action="store_true", default=False,
#                     help="print run_cmd")
args = parser.parse_args()

# if len(sys.argv)==1:
#     parser.parse_args(['-h'])

#88888888888888888888888888888888888888888888888888888888888888888888888888888888888888888
#   Logger

logger = logging.getLogger("run_parallel_blast")
#
# We are interesting in all messages
#
if args.verbose:
    logger.setLevel(logging.DEBUG)
    stderrhandler = logging.StreamHandler(sys.stderr)
    stderrhandler.setFormatter(logging.Formatter("    %(message)s"))
    stderrhandler.setLevel(logging.DEBUG)
    logger.addHandler(stderrhandler)


#88888888888888888888888888888888888888888888888888888888888888888888888888888888888888888
#   Pipeline tasks

# samples_length = {'L374N': 115, 'L374T': 115}   #, 'L444N': 104, 'L444T': 104, 'L550N': 104, 'L550T': 104}
samples_length = eval(args.sample_id_length)
sample_map_read_num = eval(args.sample_map_read_num )
if type(samples_length) != dict:
    raise Exception('sample_id_length的格式不对')
# if len(samples_length)<2:
#     raise Exception('样品数量至少是 2个.')

# sample_ids = sorted(samples_length.keys())  # sample_ids = ['L374N', 'L374T']
sample_ids = samples_length.keys()  # sample_ids = ['L374N', 'L374T']
# id_all = '%s_%s' % tuple(sample_ids)  # L374N_L374T
id_all = '_'.join(sample_ids)

anotions = ['SE', 'A3SS', 'A5SS', 'MXE', 'RI']
# anotions = ['SE', 'A3SS', 'A5SS', 'MXE']

modify_bam_index_para = []
for sample_id in sample_ids:
    one = []
    one.append('%s_map/accepted_hits.bam' % sample_id)
    one.append('%s_map/accepted_hits_modify.bam' % sample_id)
    modify_bam_index_para.append(one)

@files(modify_bam_index_para)
def modify_bam(infile, outfile):
    run_cmd('modify_bam %s %s' % (infile, outfile))

@transform(modify_bam, suffix('.bam'), '.bam.bai')
def index_bam(infile, outfile):
    run_cmd('samtools index %s' % infile)

run_events_analysis_para = []
for sample_id in sample_ids:
    for anotion in anotions:
        one = []
        one.append('%s_map/accepted_hits_modify.bam' % sample_id)
        one.append('%s_miso/complete_flag/flag.%s.%s.compute-genes-psi-complete' % (sample_id, sample_id, anotion))
        one.append(sample_id)
        one.append(anotion)
        run_events_analysis_para.append(one)

@follows(index_bam)
@files(run_events_analysis_para)
def run_events_analysis(infile, outfile, sample_id, anotion):
    run_cmd("run_events_analysis.py --compute-genes-psi /home/sgguo/database/human/h19/misopy/index/%(anotion)s %(bamfile)s --output-dir %(sample_id)s_miso/%(anotion)s --read-len %(length)s -p 5" % {'anotion': anotion, 'sample_id':sample_id, 'bamfile':infile, 'length':samples_length[sample_id]})
    flagdir = '%s_miso/complete_flag' % sample_id
    if not path(flagdir).exists():
        path(flagdir).mkdir()
    open(outfile, 'w')

@transform(run_events_analysis, suffix('.compute-genes-psi-complete'), '.summarize-samples-complete')
def run_miso_summarize_samples(infile, outfile):
    para = infile.split('.')
    para = {'sample_id': para[-3], 'anotion': para[-2]}
    run_cmd("run_miso.py --summarize-samples %(sample_id)s_miso/%(anotion)s %(sample_id)s_miso/" % para)
    open(outfile, 'w')

@transform(run_miso_summarize_samples, suffix('.summarize-samples-complete'), '.summary_add_type_complete')
def summary_add_type(infile, outfile):
    para = infile.split('.')
    para = {'sample_id': para[-3], 'anotion': para[-2]}
    run_cmd("perl /home/sgguo/script/add_type.pl %(sample_id)s_miso/summary/%(anotion)s.miso_summary %(anotion)s  %(sample_id)s_miso/summary/%(anotion)s.miso_summary_add" % para)
    if para['anotion'] == 'SE':
        run_cmd("head -1 %(sample_id)s_miso/summary/%(anotion)s.miso_summary_add > %(sample_id)s_miso/summary/header.txt" % para)
    run_cmd("sed -i 1d %(sample_id)s_miso/summary/%(anotion)s.miso_summary_add" % para)
    open(outfile, 'w')

merge_summary_para = []
for sample_id in sample_ids:
    one = []
    one.append('%s_miso/complete_flag/flag.%s.SE.summary_add_type_complete' % (sample_id, sample_id))
    one.append('%(id)s_miso/summary/%(id)s_miso.sumarize_all_events.bf' % {'id':sample_id})
    one.append(sample_id)
    merge_summary_para.append(one)
@follows(summary_add_type)
@files(merge_summary_para)
def merge_summary(infile, outfile, sample_id):
    run_cmd("cat %(id)s_miso/summary/*.miso_summary_add > %(bf)s" % {'id':sample_id, 'bf':outfile})

def run_miso_compare_samples_para():
    for anotion in anotions:
        one = []
        one.append('%s_miso/complete_flag/flag.%s.%s.compute-genes-psi-complete' % (sample_ids[0], sample_ids[0], anotion))
        one.append('%(id_all)s_miso_comparisons/complete_flag/flag.%(id_all)s.%(anotion)s.compare_complete' % {'id_all': id_all, 'anotion':anotion})
        one.append(anotion)
        one.append(sample_ids[0])
        one.append(sample_ids[1])
        # run_miso_compare_samples_para.append(one)
        yield one
# print '#######'
# print run_miso_compare_samples_para[0]
# print '#######'

@follows(run_events_analysis)
@files(run_miso_compare_samples_para)
def run_miso_compare_samples(infile, outfile, anotion, id1, id2):
    para = {'anotion':anotion, 'id_one':id1, 'id_two':id2, 'id_all': id_all}
    run_cmd("run_miso.py --compare-samples %(id_one)s_miso/%(anotion)s %(id_two)s_miso/%(anotion)s %(id_all)s_miso_comparisons/" % para)
    flag_dir = '%s_miso_comparisons/complete_flag' % id_all
    if not path(flag_dir).exists():
        path(flag_dir).mkdir()
    open(outfile, 'w')

@transform(run_miso_compare_samples, suffix('.compare_complete'), '.compare_addtype_complete')
def compare_add_type(infile, outfile):
    anotion = infile.split('.')[-2]
    para = {'id_all':id_all, 'anotion':anotion}
    run_cmd("perl /home/sgguo/script/add_type.pl %(id_all)s_miso_comparisons/%(anotion)s_vs_%(anotion)s/bayes-factors/%(anotion)s_vs_%(anotion)s.miso_bf %(anotion)s %(id_all)s_miso_comparisons/%(anotion)s_vs_%(anotion)s/bayes-factors/%(anotion)s_vs_%(anotion)s.miso_bf_add" % para)
    if anotion=='SE':
        run_cmd('head -1 %(id_all)s_miso_comparisons/%(anotion)s_vs_%(anotion)s/bayes-factors/%(anotion)s_vs_%(anotion)s.miso_bf_add > %(id_all)s_miso_comparisons/header.txt' % para)
    run_cmd("sed -i 1d %(id_all)s_miso_comparisons/%(anotion)s_vs_%(anotion)s/bayes-factors/%(anotion)s_vs_%(anotion)s.miso_bf_add" % para)
    open(outfile, 'w')

@transform(run_miso_compare_samples, suffix('.compare_complete'), '.filter_events_complete')
def filter_events(infile, outfile):
    anotion = infile.split('.')[-2]
    para = {'id_all':id_all, 'anotion':anotion}
    run_cmd("filter_events.py --filter %(id_all)s_miso_comparisons/%(anotion)s_vs_%(anotion)s/bayes-factors/%(anotion)s_vs_%(anotion)s.miso_bf  --num-inc 1 --num-exc 1 --num-sum-inc-exc 10 --delta-psi 0.20 --bayes-factor 10 --output-dir %(id_all)s_miso_comparisons/%(anotion)s_vs_%(anotion)s/bayes-factors/" % para)
    open(outfile, 'w')

@transform(filter_events, suffix('.filter_events_complete'), '.filter_add_type_complete')
def filter_add_type(infile, outfile):
    anotion = infile.split('.')[-2]
    para = {'id_all':id_all, 'anotion':anotion}
    run_cmd("perl /home/sgguo/script/add_type.pl %(id_all)s_miso_comparisons/%(anotion)s_vs_%(anotion)s/bayes-factors/%(anotion)s_vs_%(anotion)s.miso_bf.filtered %(anotion)s %(id_all)s_miso_comparisons/%(anotion)s_vs_%(anotion)s/bayes-factors/%(anotion)s_vs_%(anotion)s.miso_bf.filtered_add" % para)
    run_cmd("sed -i 1d %(id_all)s_miso_comparisons/%(anotion)s_vs_%(anotion)s/bayes-factors/%(anotion)s_vs_%(anotion)s.miso_bf.filtered_add" % para)
    open(outfile, 'w')

@follows(compare_add_type)
@files('%s_miso_comparisons/complete_flag/flag.%s.SE.compare_complete' % (id_all, id_all), '%s_miso_comparisons/%s.all_events.bf' % (id_all, id_all))
def merge_compare_add_type(infile, outfile):
    run_cmd("cat %s_miso_comparisons/*/*/*.miso_bf_add > %s" % (id_all, outfile))

@follows(filter_add_type)
@files('%s_miso_comparisons/complete_flag/flag.%s.SE.filter_add_type_complete' % (id_all, id_all), '%s_miso_comparisons/%s.filter_all_events.bf' % (id_all, id_all))
def merge_filter_add_type(infile, outfile):
    run_cmd("cat %s_miso_comparisons/*/*/*.miso_bf.filtered_add > %s" % (id_all, outfile))


@transform(merge_filter_add_type, regex(r'.filter_all_events.bf$'), '_raw_events.tsv')
def raw_events_tsv(infile, outfile):
    run_cmd('perl /home/sgguo/script/add_pairwise.pl %s %s %s' % (infile, id_all, outfile))
    run_cmd("sed -i 1i'group\ttype\tevent_name\tsample1_posterior_mean\tsample1_ci_low\tsample1_ci_high\tsample2_posterior_mean\tsample2_ci_low\tsample2_ci_high\tdiff\tbayes_factor\tisoforms\tsample1_counts\tsample1_assigned_counts\tsample2_counts\tsample2_assigned_counts\tchrom\tstrand\tmRNA_starts\tmRNA_ends' %s" % outfile)

@follows(raw_events_tsv)
@files('%s_miso_comparisons/%s_raw_events.tsv' % (id_all, id_all), '%s_miso_comparisons/dsg-result/dsg_list.tsv' % id_all)
def generate_dsg_list_tsv(infile, outfile):
    dsg_result_dir = path('%s_miso_comparisons/dsg-result' % id_all)
    if not dsg_result_dir.exists():
        dsg_result_dir.mkdir()
    run_cmd('Rscript /home/sgguo/python/R_bin/generate_dsg_list_tsv.R %s %s %s_miso_comparisons/dsg-result/dsg_list_furtherfiltered.tsv /home/sgguo/database/human/human_event2gene_ref_0.4above.txt' % (infile , outfile , id_all))


# @follows(run_miso_compare_samples)
# @files('%(id_all)s_miso_comparisons/complete_flag/flag.%(id_all)s.SE.compare_complete' % {'id_all': id_all}, '%s_miso_comparisons/complete_flag/flag.%s.ln_bamfiles_complete' % (id_all, id_all))
@merge(run_miso_compare_samples, '%s_miso_comparisons/complete_flag/flag.%s.ln_bamfiles_complete' % (id_all, id_all))
def ln_bamfiles(infile, outfile):
    bam_dir = path('%s_miso_comparisons/dsg-result/bam' % id_all)
    if not bam_dir.exists():
        bam_dir.makedirs()
    for sample_id in sample_ids:
        para = {'id': sample_id, 'id_all': id_all, 'pwd': str(path('./').abspath())}
        run_cmd('ln -sf %(pwd)s/%(id)s_map/accepted_hits_modify.bam %(id_all)s_miso_comparisons/dsg-result/bam/%(id)s.bam' % para)
        run_cmd('ln -sf %(pwd)s/%(id)s_map/accepted_hits_modify.bam.bai %(id_all)s_miso_comparisons/dsg-result/bam/%(id)s.bam.bai' % para)
    open(outfile, 'w')

@transform(ln_bamfiles, suffix('.ln_bamfiles_complete'), '.generate_setfile_complete')
def generate_setfile(infile, outfile):
    setfile = open('%s_miso_comparisons/dsg-result/plot_settings.txt' % id_all, 'w')
    para = {'id_one': sample_ids[0], 'id_two':sample_ids[1], 'id_all': id_all}
    config = ConfigParser.ConfigParser()
    configfile = open('/software/Python/Python274/lib/python2.7/site-packages/misopy/settings/sashimi_plot_settings.txt', 'r')
    config.readfp(configfile)
    # bam_prefix =
    config.set('data', 'bam_prefix', '%(id_all)s_miso_comparisons/dsg-result/bam/' % para)
    config.set('data', 'miso_prefix', './')
    config.set('data', 'bam_files', "['%(id_one)s.bam', '%(id_two)s.bam']" % para)
    miso_files = []
    for anotion in anotions:
        miso_files.append('%s_miso/%s/' % (sample_ids[0], anotion))
        miso_files.append('%s_miso/%s/' % (sample_ids[1], anotion))
    config.set('data', 'miso_files', str(miso_files))
    config.set('plotting', 'coverages', "[%s, %s]" % (sample_map_read_num[sample_ids[0]], sample_map_read_num[sample_ids[1]]))
    colors = eval(config.get('plotting', 'colors'))
    config.set('plotting', 'colors', str(colors[0:4:2]))

    config.write(setfile)
    setfile.close()

    open(outfile, 'w')


sashimi_plots_para = []
for anotion in anotions:
    one = []
    one.append('%s_miso_comparisons/complete_flag/flag.%s.generate_setfile_complete' % (id_all, id_all))
    one.append('%s_miso_comparisons/complete_flag/flag.%s.%s.sashimi_plots_complete' % (id_all, id_all, anotion))
    sashimi_plots_para.append(one)

@follows(generate_dsg_list_tsv, generate_setfile)
@files(sashimi_plots_para)
def sashimi_plots(infile, outfile):
    anotion = outfile.split('.')[-2]
    run_cmd('perl /home/sgguo/script/sashimi_plots.pl %(id_all)s_miso_comparisons/dsg-result/dsg_list.tsv /home/sgguo/database/human/h19/misopy/index/%(anotion)s %(id_all)s_miso_comparisons/dsg-result/sashimi_plots %(id_all)s_miso_comparisons/dsg-result/plot_settings.txt %(anotion)s' % {'id_all': id_all, 'anotion': anotion})
    open(outfile, 'w')


# exce_task = eval(args.task)
# exce_tasks = [exce_task]
exce_tasks = [merge_compare_add_type, merge_summary, sashimi_plots]  # 这是运行所有的模块
# exce_tasks = [merge_summary]
if args.just_print:
    pipeline_printout(sys.stdout, exce_tasks, verbose=args.verbose)
elif args.flowchart:
    # use file extension for output format
    output_format = os.path.splitext(args.flowchart)[1][1:]
    pipeline_printout_graph (open(args.flowchart, "w"),
                             output_format,
                             exce_tasks,
                             no_key_legend = True)
    os.system('eog %s' % args.flowchart)
else:
    pipeline_run(exce_tasks,  multiprocess = args.jobs,
                        logger = logger, verbose=args.verbose)

