#!/usr/bin/env python
#encoding=utf8
from __future__ import division, unicode_literals, print_function
from future_builtins import map, zip
import argparse
import pysam

'''

'''


def main():
    function = ''
    parser = argparse.ArgumentParser(description=function)
    parser.add_argument('inbam', help='inbam.bam')
    parser.add_argument('tobam', help='tobam.bam')
    args = parser.parse_args()
    modify_bam(args)

def modify_bam(args):
    inbam = pysam.Samfile(args.inbam, 'rb')
    bam_header = inbam.header
    for sq in bam_header['SQ']:
        sq['SN'] = ''.join(['chr', sq['SN']])
    tobam = pysam.Samfile(args.tobam, 'wb', header = bam_header)
    for read in inbam:
        tobam.write(read)
    inbam.close()
    tobam.close()
    print('### Success::: bamfile %s modiy !' % args.inbam)

if __name__ == '__main__':
    print()
    main()
    print('\nSuccess!!!\n')

