#!/usr/bin/env python
#encoding=utf8
import argparse, time , sys
from otu_biom_lib import stat, tocsv, trim, del_repeat

def main():
    function = 'biom文件的处理'
    parser = argparse.ArgumentParser(description=function)
    subparsers = parser.add_subparsers(title='subcommands',help='sub-command help',
        description='Choose a command to perform the corresponding operation.')

    statParse = subparsers.add_parser('stat', help="statistics Sample's OTU infomation")
    statParse.add_argument('biomfp', help='biom file')
    statParse.set_defaults(func=stat)

    tocsvParse = subparsers.add_parser('tocsv',
                            help='get data of biom to csv')
    tocsvParse.add_argument('biomfp', help='biom file')
    tocsvParse.add_argument('toDir', help='save the matrix of biom as csv to Dir')
    tocsvParse.set_defaults(func=tocsv)


    trimParse = subparsers.add_parser('trim',
                        help="del sample's OTU that read number less than critical")
    trimParse.add_argument('biomfp', help='biom file')
    trimParse.add_argument('critical', help="when less than this critiacal, del the OTU'number, trim的阈值, 默认为5, 即把小于等于5的样品otu设为0",
                        type=int, default=5)
    trimParse.add_argument('toDir', help='save the matrix of biom as csv to Dir')
    trimParse.set_defaults(func=trim)

    del_repeatParse = subparsers.add_parser('del_repeat',
                        help="删除重复的otu聚类")
    del_repeatParse.add_argument('biomfp', help='biom file')
    del_repeatParse.add_argument('toDir', help='save the del_repeat otu of biom to Dir')
    del_repeatParse.set_defaults(func=del_repeat)


    # if len(sys.argv)==1:
    #     parser.parse_args(['-h'])
    # args = parser.parse_args()
    # args.func(args)

if __name__ == '__main__':
    main()
