#!/usr/bin/env python
#encoding=utf8
from __future__ import division
import argparse
from michelia import cond


def main():
    function = ''
    parser = argparse.ArgumentParser(description=function)
    parser.add_argument("sh_script",
                        help="shell脚本文件或命令如 'll ./dir'")
    parser.add_argument("num", type=int, default=1)
    parser.add_argument('-l', type=int, metavar='Last', help='Last base to keep. Default is entire read.')
    args = parser.parse_args()


if __name__ == '__main__':
    main()

